version: '3'

services:

  backend:
    image: dmitrukv/poll-service:1.0.0
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DSN=postgresql://postgres:postgres@postgres/mydb?sslmode=disable&timezone=UTC
      - MEMCACHED=memcached:11211

  memcached:
    image: memcached:1.6.18
    expose:
      - 11211

  postgres:
    image: postgres:14.6
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb