version: '3'

services:

  memcache:
    image: memcached:1.6.18
    ports:
      - 11211:11211

  postgres:
    image: postgres:14.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: polls-db